### ISSUE TITLE
[REQUEST] - Ability to specify specific episodes in a season for TV

### ISSUE THREAD

**Issue by kingfenix** [tidusjar/PlexRequests.Net#254]
So I get facebook messages from my daughter who says, I need such and such episode of this show, you deleted it too soon...

Would be great if she could do this on the request app.

Thanks,
Doug

**Comment by tidusjar** [comment]
Well you need to tell her to watch it in a timely fashion!  :laughing: 

So I have just added in selecting seasons, I'm not sure how requesting episodes would fit in with the application but i'll have a think.

**Comment by kingfenix** [comment]
totally agree on the timely fashion, but she is 19 and learned from her mother so....I appreciate your time and effort, and LOVE plexrequests.net, to me this is the first usable attempt anyone has made.

**Comment by kamikasky** [comment]
My friends and I like to download specific episodes very often as well. Only reason I have not made PlexRequests my main as opposed to HTPCManager

**Comment by tidusjar** [comment]
Got some bad news. 

Yesterday while working on this I found a bug in Sonarr. 
The bug is that I cannot add a new series into Sonarr (using the API) as unmonitored.

So if a user requests 5 episodes from a series that doesn't yet exist in Sonarr, I try and add the series as unmonitored and then monitor the episodes the user has selected... But this doesn't work.

For now I am going to have to hack around it and add the series as Monitored and then unmonitor it straight away :(  

Sonarr Issue reference: https://github.com/Sonarr/Sonarr/issues/1404

They have fixed it in devlop but there is no ETA on them going live.

So hack around it for now, in a few months time i'll come back and do it properly.

**Comment by tidusjar** [comment]
TODO: We need to lookup the episodes monitored on Sonarr if the series exists. If the episode is already monitored then pre-tick the UI.

**Comment by tidusjar** [comment]
This is now ready for someone to test if they are feeling brave!

**Comment by tidusjar** [comment]
https://ci.appveyor.com/project/tidusjar/requestplex/build/artifacts

**Comment by kamikasky** [comment]
Thanks for your hard work! I'm on vacation at the moment so I will have to check it out when I get back!

**Comment by whitecollar17** [comment]
Its look like sonarr pushed a update with fixing the problem

" Allow series to be added unmonitored through the API"

**Comment by tidusjar** [comment]
Yeah they did :) But I'll leave the work around in place for a bit since not everyone updates straight away
