### ISSUE TITLE
Request TV Series, Select a certain season

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/PlexRequests.Net#26]
New dropdown option > open a modal with all seasons available. Pick an individual season to download.

**Comment by curlz620** [comment]
This would be amazing. since a lot of users request an entire show with 20+ seasons and only want the last two. If a user selects season 5 and its currently airing season 7 would it start grabbing the new episodes as they air? I could see a user wanting to request season 5,6, and 7 and all new episodes.

**Comment by tidusjar** [comment]
There would be a list of seasons in some sort of modal where they can check (checkboxes) what ones they are requesting.
