### ISSUE TITLE
Movies recognition

### ISSUE THREAD

**Issue by MiuiSwitzerland** [tidusjar/PlexRequests.Net#330]
#### Plex Requests.Net Version:

1.7.5

#### Operating System:

Ubuntu 15.04

#### Mono Version:

4.2.3

#### Reproduction Steps:

PlexRequests is not recognizing Movies properly and the search suddenly doesn't seem to be accurate anymore.

I usually name my Movies based on IMDB title. For example I was searching for **The Quiet Hour (2015)** however at IMDB this movie is dated **The Quiet Hour (2014)** and PlexRequests will not mark this Movie as available which is bit of a problem if my users keeps on requesting it. 

Another example is the Movie which is labeled at IMDB **Allegiant (2016)**. If I search it on PlexRequests, the search results in **The Divergent Series: Allegiant (2016)** which will also leave the Movie unavailable because my Movie folder is labeled **Allegiant (2016)**

There are as well some others that are not recognized even with the right Title and Year like on the screenshots bellow:

This is the PlexRequests page:

![movies](https://cloud.githubusercontent.com/assets/1059104/16186798/dd8cbf86-36cc-11e6-8c1e-cb7eb7343738.JPG)

This is a part of my Movies folder:

![movies1](https://cloud.githubusercontent.com/assets/1059104/16186811/eb1fc378-36cc-11e6-9944-4a4ef2a06f42.JPG)

**Comment by tidusjar** [comment]
Hi,
In regards to any data issues with the search, I have no control over this.This will need to be reported over at TvMaze (I report whatever I can find, but I can do it all :) ).
Yes the way the current release build is searching Plex is not ideal, it was a workaround since the Plex API has no official documentation. Since then I have learn't a few things about Plex and how it works, In the dev build there is a new setting (Advanced Plex Search). This new settings is a bit more intensive but it will have a 99% accurate match (we match on IMDB Id's and TheTVDB Id's). This will work straight away for movies since we already have the IMDB id's, but for TV Shows it will only work for new requests since we now have to also capture the TheTvDB id.
Timescale for the next release is currently Unknown, (Hopefully soon) I just need to find some time and fix some bugs.
Jamie

Date: Mon, 20 Jun 2016 01:32:10 -0700
