### ISSUE TITLE
Movie Not Detecting Properly

### ISSUE THREAD

**Issue by halorrr** [tidusjar/PlexRequests.Net#370]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.8.2

#### Operating System:
10.11.5

#### Mono Version:
4.4

#### Reproduction Steps:
Requesting movie not always detecting that the movie is already in the library for some items.

Screenshot of the movies in CouchPotato library:
![cp](https://cloud.githubusercontent.com/assets/1358708/16318695/4563a65e-395e-11e6-9669-8e3798603d3a.jpg)

Screenshot of the movies in Plex library:
![plex](https://cloud.githubusercontent.com/assets/1358708/16318700/4bcde072-395e-11e6-8f08-7d434b7e1447.jpg)

Yet when I search for all those movies, for some reason it doesn't detect the movie"127 Hours". It seems very random as to the movies it does this for.

Video showing it:
http://screencast.com/t/2uZwoKNny

**Comment by tidusjar** [comment]
Go in the settings and turn on the advanced Plex search. Then restart Plex requests for it to scan.

**Comment by halorrr** [comment]
I actually already have that on from when I originally set up PlexRequests and I've restarted many times since then.

**Comment by tidusjar** [comment]
Hmmm. I'll take a look into it.

**Comment by tidusjar** [comment]
@halorrr is this still an issue?

**Comment by klusion** [comment]
I am sir. Should I open a separate ticket? What logs can I provide you? I am on Windows 10 and running the most recent version though the issue started several versions ago. I have tried install PlexRequests from scratch as well.

**Comment by tidusjar** [comment]
Hi @klusion 

So can you provide me with some examples of what you are searching for and it not detecting it?

Can you also tell me your settings? e.g. do you have advanced search on?

**Comment by klusion** [comment]
Searching for tv shows appropriately detects availability within Plex, so no problems there. The problem occurs searching for movies. For instance, typing in "Star Wars" on lists Star Wars Episode 1 (whomp whomp) as available, but not Episodes 2-7, though both CouchPotato and Plex detect them. The Revenant is another example.

I do currently have "advanced search" on but not "episode search". Actually, I can't turn off "advanced search". I've tried a couple of times but it repopulates every time, so that's kinda odd. I am using reverse proxy, but connectivity tests pass for Plex, CouchPotato, and Sonarr.

**Comment by halorrr** [comment]
Sorry for the delayed response but I can confirm this is still and issue for me as well.
