### ISSUE TITLE
Add "Any Requests Added" email notice

### ISSUE THREAD

**Issue by baerface** [tidusjar/PlexRequests.Net#504]
Not sure I've seen this Enhancement Request.. If it's out there, or already exists somehow, sorry. 

I, along with my user base, would love to have a notification when ANYTHING becomes available.. Not just what they have requested.

I'm thinking you could have 2 options. 

Send me a notification when items I have requested have been added.  (Currently there)
Send me a notification when items anyone has requested have been added.

Could get even more granular, and each notification based on movie/tv/music.

**Comment by tidusjar** [comment]
That's a good idea. 

Should be quite easy to do as well due to the way that part of the system has been architected

**Comment by leram84** [comment]
I was about to make a new post for this, before i saw this here. I would like the same thing, but specifically, i think it would be good to get a button for "Notify me" when search turns up an item that has already been requested by another user. I'm correct in my understanding that right now, only the requester can get a notification right?

**Comment by tidusjar** [comment]
Yeah that's right, This is still planned :)

**Comment by tidusjar** [comment]
Does the Recently Added newsletter fill this requirement or not?

**Comment by leram84** [comment]
newsletter looks pretty cool! any way to get a web version? anyway, it probably will close op's issue, but i still would like the option to get individual notifications for specific items a user requests.

Actually this gives me another idea for a whole new can of worms. If you do plan on a web version of the newsletter (like plexemail has), I could see it also acting as a hub for each users entire request history/availability. So the top tabs would be something like "Movies" (added to plex in the last week, or since the last time you viewed this page, etc) "TV", and "My requests" (both fulfilled and pending). Could maybe even add a tab for "My issues" (which is something else that could also use notifications, especially if the issue is that a file is unplayable)...... lol, maybe i should just make a new post?

**Comment by SuperPotatoMen** [comment]
@leram84 Can you make a new post for that? There are pretty good idea's!
