### ISSUE TITLE
Errors connecting to CouchPotato via TLS

### ISSUE THREAD

**Issue by ghost** [tidusjar/PlexRequests.Net#525]
#### Plex Requests.Net Version:
1.9.1

#### Operating System:

Docker container from rogueosb

#### Mono Version:

rogueosb's Docker container.

#### Applicable Logs (from `/logs/` directory or the Admin page):

System.Net.WebException: Error: SendFailure (Error writing headers) ---> System.Net.WebException: Error writing headers ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010f at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (IAsyncResult asyncResult) <0x40b471f0 + 0x00107> in :0 at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (IAsyncResult ar, Boolean ignoreEmpty) <0x40b47140 + 0x0002b> in :0 at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (IAsyncResult result) <0x40b41680 + 0x0021f> in :0 --- End of inner exception stack trace --- at System.Net.WebConnection.EndWrite (System.Net.HttpWebRequest request, Boolean throwOnError, IAsyncResult result) <0x40b8a370 + 0x00207> in :0 at System.Net.WebConnectionStream+c__AnonStorey1.<>m__0 (IAsyncResult r) <0x40b89cd0 + 0x0012b> in :0 --- End of inner exception stack trace --- --- End of inner exception stack trace --- at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x40b2eb20 + 0x00197> in :0 at System.Net.HttpWebRequest.GetResponse () <0x40b2aa70 + 0x00053> in :0 at RestSharp.Http.GetRawResponse (System.Net.HttpWebRequest request) <0x40b2a6d0 + 0x00043> in :0 

#### Reproduction Steps:

Start rogueosb's Docker container, connect to CouchPotato, wait for error.

**Comment by SoftBrok** [comment]
The "test connectivity" option shows a successful connection, but requests do not show up and PlexRequests is unable to request new media. Restarts do not have any effect.

**Comment by tidusjar** [comment]
You got an untrusted cert on CP?

**Comment by SoftBrok** [comment]
It is trusted by Microsoft EDGE, iOS 9.3.5, Chrome, Firefox, and similar. It is a certificate issued by Comodo and costs $9.95 per year.

**Comment by tidusjar** [comment]
I think the mono certs are not trusted on your machine.
Can you try this:

    mozroots --import --ask-remove 

> Info about [mozroots](http://linux.die.net/man/1/mozroots)

**Comment by SoftBrok** [comment]
Is that on the host, in the Docker container, both, or..?

Thank you for the insight. That helps a lot.

**Comment by tidusjar** [comment]
Errrr, not too sure about that with Docker

**Comment by SoftBrok** [comment]
The problem came back. We need an option to ignore validating the certificate. This is becoming a major stability issue that is impacting my system.

**Comment by SoftBrok** [comment]
System.Net.WebException: Error: SendFailure (Error writing headers) ---> System.Net.WebException: Error writing headers ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010f at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (IAsyncResult asyncResult) <0x418b2ff0 + 0x000ff> in :0 at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (IAsyncResult ar, Boolean ignoreEmpty) <0x418b2f40 + 0x0002b> in :0 at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (IAsyncResult result) <0x418ad860 + 0x0021b> in :0 --- End of inner exception stack trace --- at System.Net.WebConnection.EndWrite (System.Net.HttpWebRequest request, Boolean throwOnError, IAsyncResult result) <0x418f3950 + 0x00207> in :0 at System.Net.WebConnectionStream+c__AnonStorey1.<>m__0 (IAsyncResult r) <0x418f32b0 + 0x0012b> in :0 --- End of inner exception stack trace --- --- End of inner exception stack trace --- at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x4189ad90 + 0x00197> in :0 at System.Net.HttpWebRequest.GetResponse () <0x41896ce0 + 0x00053> in :0 at RestSharp.Http.GetRawResponse (System.Net.HttpWebRequest request) <0x41896940 + 0x00043> in :0 

If it would ignore validating the certificate when the server is trying to connect to itself, it would work fine. I am getting these errors on an otherwise perfect system. I just need to disable validation it doesn't need.

**Comment by tidusjar** [comment]
I am not sure what I can do about this since Mono itself doesn't trust the certificates. Did you perform the moz roots thing?

**Comment by SoftBrok** [comment]
Yes, it no longer fixes the issue.

**Comment by SoftBrok** [comment]
I found a workaround. The certificate can be forced into the certificate trust store by putting the cabundle contents into a file such as:

/usr/local/share/ca-certificates/override.crt

and running the following next:

update-ca-certificates

The certificate is installed correctly. I am not sure why this is needed.

**Comment by SoftBrok** [comment]
I should say that other servers can hit it no problem. It just seems to be a problem with that Docker container/mono/something.

**Comment by SoftBrok** [comment]
Okay, all attempts to work around this have failed. I can't make it validate what it refuses to validate. It simply will not work. I've used moz-roots, I've added the ca-bundle to the trust store, I've done everything I can literally think of to make it work. It simply won't.

PlexRequests.net needs to have an option to bypass certificate validation. It is becoming an extremely bad usability issue.

**Comment by tidusjar** [comment]
You are welcome to implement it @SoftBrok 

Currently this is not on my priority list and I don't have much free time nowadays.

**Comment by SoftBrok** [comment]
Thank you for the confirmation. I will switch to the meteor version.

**Comment by SoftBrok** [comment]
I have also left a comment on the reddit thread recommending others to do the same:

https://www.reddit.com/r/PleX/comments/52kbdc/rplexs_tool_tuesday_thread_20160913_plex_requests/d7r3ddo
