### ISSUE TITLE
Question about newsletter

### ISSUE THREAD

**Issue by apperrault** [tidusjar/PlexRequests.Net#650]
Hi there. I have a question about the newsletter function. I have 5 local users on my Plex. None of them have Plex accounts but I would like to be able to send them a weekly newsletter type email about what was added. Do I need to install Plex email or will Plex requests do this for me. I can't find a place to associate an email address with local users in Plex. 

Thanks

App

**Comment by SuperPotatoMen** [comment]
That is possible  just add the email adress in the setting page in you're admin panel

![image](https://cloud.githubusercontent.com/assets/2944704/19951078/eaa743c2-a15b-11e6-9298-3e0385cf3859.png)

**Comment by naq90** [comment]
I do not see this option in my settings panel. Email notification have been set up. I received the test email as well. I am on the latest version. 

![screen shot 2016-11-02 at 9 59 35 pm](https://cloud.githubusercontent.com/assets/7684792/19954638/ce094436-a147-11e6-9d81-97c763ad7138.png)
![screen shot 2016-11-02 at 9 59 49 pm](https://cloud.githubusercontent.com/assets/7684792/19954639/ce09a3f4-a147-11e6-84d4-46c180736329.png)

**Comment by SuperPotatoMen** [comment]
Can you clear you're browser cache?  I don't see the newsletter setting button on the left.

**Comment by Nvious1** [comment]
I also had a question.  I currently have the quartz schedule as 0 0 6 1/1 * ? * which should run every day at 6 am local time, however I didn't receive the email until 7:37 AM.  I don't think it took that long to run but was wondering if there was many some kind of issue with the quartz scheduling.

Also could you explain how the newsletter determines what content its going to display?  I would anticipate it only captures the changes in the libraries since the last time it was run but I am not sure if its behaving that way or if it should?

**Comment by tidusjar** [comment]
Why it took so long to fire off, not too sure about that. 

Currently with the newsletter, Plex exposes some information of recently added media, all I do is grab that information and display it. 

I do not check if we have already sent that item yet.

**Comment by naq90** [comment]
@SuperPotatoMen I tried clearing the cache to no avail. Should I try to reinstall?

**Comment by SuperPotatoMen** [comment]
Yeah, its strange beceause its in the 1.9.6 version. Can you re install it? I hope its a big deal for you?

**Comment by tidusjar** [comment]
Did you ensure you overwrote everything?
