### ISSUE TITLE
URL for Users

### ISSUE THREAD

**Issue by johnballjr** [tidusjar/PlexRequests.Net#768]
Hi All. Newbie here.  I've installed Plex Requests and setup CP and SickRage.
This is a stupid question, but . . . What URL do I give my friends to make requests? I do not see anything within Plex after they log in.  Any help would be greatly appreciated!

Thanks

**Comment by SuperPotatoMen** [comment]
Hi, 

This is a stand alone set-up. You can open your browser en go to local:3579
For other users outsite of you home network, you need to portforward port 3579 to you computer en open the firewall for that port.

**Comment by bromanguydude** [comment]
@johnballjr I would use No-Ip.com and get a free DNS name like plexrequests.ddns.net:3579. They have a program that runs on your server and will check your public address every couple of minutes in case it changes because you have a residential dynamic IP. You can then open that server up to the outside world and forward all incoming connections on your public IP address to that server on that port. If you would like a simpler name for your friends to remember you can use Godaddy or Wix to purchase one and then forward your free DNS name to your paid one.
