### ISSUE TITLE
Newsletter format

### ISSUE THREAD

**Issue by whatupcraig** [tidusjar/PlexRequests.Net#802]
I sent myself a test email from the interface. The email sent fine, however, before each section, movies and tv shows, there are a bunch of lines. How do I get rid of that, if possible?

![image](https://cloud.githubusercontent.com/assets/20756018/21292239/dba55a30-c4ba-11e6-8255-4d0bfc7f3069.png)

**Comment by chrisausbun** [comment]
I've actually been opening it up in outlook and customizing myself self to make it look like it should and delete everything that isn't recently added until @tidusjar can fix the formatting and fix which libraries are on the newsletter since it displays way more than just what was recently added.

Hopefully, that's helps until the newsletter can be perfected.

On Dec 17, 2016, at 11:42 PM, whatupcraig <notifications@github.com<mailto:notifications@github.com>> wrote:


I sent myself a test email from the interface. The email sent fine, however, before each section, movies and tv shows, there are a bunch of lines. How do I get rid of that, if possible?

[image]<https://cloud.githubusercontent.com/assets/20756018/21292239/dba55a30-c4ba-11e6-8255-4d0bfc7f3069.png>

-

**Comment by SuperPotatoMen** [comment]
Pleas use our bug report form and open a new issue
